### ISSUE TITLE
Authentication with an expired token receives a weird message.

### ISSUE THREAD

**Issue by ilyavf** [donejs/bitcentive#279]
```
420["authenticate",{"strategy":"jwt","accessToken":"expired_token_here"}]
```

"NotAuthenticated: invalid signature↵    at NotAuthenticated.ExtendableBuiltin (/Users/ilya/dev/bitcentive/node_modules/feathers-errors/lib/index.js:21:28)↵    at NotAuthenticated.FeathersError (/Users/ilya/dev/bitcentive/node_modules/feathers-errors/lib/index.js:96:116)↵    at new NotAuthenticated (/Users/ilya/dev/bitcentive/node_modules/feathers-errors/lib/index.js:149:117)↵    at /Users/ilya/dev/bitcentive/node_modules/feathers-authentication/lib/socket/handler.js:148:33↵    at process._tickCallback (internal/process/next_tick.js:103:7)"

**Comment by ilyavf** [comment]
With the latest feathers it looks good:
```js
{
	className: "not-authenticated",
	code: 401,
	data: {
		name: "JsonWebTokenError",
		message: "invalid signature"
	},
	message: "invalid signature",
	name: "JsonWebTokenError",
	errors: {},
	message: "invalid signature",
	name: "NotAuthenticated",
	stack: "NotAuthenticated: invalid signature..."
	type: "FeathersError"
}
```
